// Login

export const ON_USERNAME_OR_EMAIL_CHANGE_LOGIN = 'ON_USERNAME_OR_EMAIL_CHANGE_LOGIN';
export const ON_PASSWORD_CHANGE_LOGIN = 'ON_PASSWORD_CHANGE_LOGIN';
export const ON_LOGIN_INITIATE = 'ON_LOGIN_INITIATE';
export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS';
export const ON_LOGIN_FAILURE = 'ON_LOGIN_FAILURE';
export const ON_CLEAR_STATUS_ERRORS_MESSAGE_LOGIN = 'ON_CLEAR_STATUS_ERRORS_MESSAGE_LOGIN';
export const ON_REMEMBER_ME_CHANGE = 'ON_REMEMBER_ME_CHANGE';

// Signup

export const ON_USERNAME_CHANGE_SIGNUP = 'ON_USERNAME_CHANGE_SIGNUP';
export const ON_EMAIL_CHANGE_SIGNUP = 'ON_EMAIL_CHANGE_SIGNUP';
export const ON_PASSWORD_CHANGE_SIGNUP = 'ON_PASSWORD_CHANGE_SIGNUP';
export const ON_CONFIRM_PASSWORD_CHANGE_SIGNUP = 'ON_CONFIRM_PASSWORD_CHANGE_SIGNUP';
export const ON_SIGNUP_INITIATE = 'ON_SIGNUP_INITIATE';
export const ON_SIGNUP_SUCCESS = 'ON_SIGNUP_SUCCESS';
export const ON_SIGNUP_FAILURE = 'ON_SIGNUP_FAILURE';
export const ON_CLEAR_STATUS_ERRORS_MESSAGE_SIGNUP = 'ON_CLEAR_STATUS_ERRORS_MESSAGE_SIGNUP';

// Navigation

export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';
export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
export const HIDE_SIGNUP_MODAL = 'HIDE_SIGNUP_MODAL';

// Categories

export const SHOW_UPLOADS_MODAL = 'SHOW_UPLOADS_MODAL';
export const HIDE_UPLOADS_MODAL = 'HIDE_UPLOADS_MODAL';

// Product Creation

export const SHOW_UPLOADS_MULTIPLE_MODAL = 'SHOW_UPLOADS_MULTIPLE_MODAL';
export const HIDE_UPLOADS_MULTIPLE_MODAL = 'HIDE_UPLOADS_MULTIPLE_MODAL';

// Upload

export const ON_CHOOSE_IMAGE = 'ON_CHOOSE_IMAGE';
export const ON_CHOOSE_MULTIPLE_IMAGES = 'ON_CHOOSE_MULTIPLE_IMAGES';

// Settings

export const ON_SITE_NAVIGATION_CHANGE = 'ON_SITE_NAVIGATION_CHANGE';
export const ON_SLIDER_IMAGES_CHANGE = 'ON_SLIDER_IMAGES_CHANGE';
export const ON_TOP_PROMOTIONAL_BANNER_CHANGE = 'ON_TOP_PROMOTIONAL_BANNER_CHANGE';

// Shopping Cart

export const ON_OPEN_SHOPPING_CART = 'ON_OPEN_SHOPPING_CART';
export const ON_CLOSE_SHOPPING_CART = 'ON_CLOSE_SHOPPING_CART';
export const REHYDRATE_SHOPPING_CART_STATE = 'REHYDRATE_SHOPPING_CART_STATE';
export const ON_ADD_PRODUCT_TO_CART = 'ON_ADD_PRODUCT_TO_CART';
export const ON_REMOVE_PRODUCT_FROM_CART = 'ON_REMOVE_PRODUCT_FROM_CART';
export const ON_EMPTY_CART = 'ON_EMPTY_CART';

// User Reducer

export const ON_GET_USER_CREDENTIALS = 'ON_GET_USER_CREDENTIALS';
