// Login

export const ON_USERNAME_OR_EMAIL_CHANGE_LOGIN = 'ON_USERNAME_OR_EMAIL_CHANGE_LOGIN';
export const ON_PASSWORD_CHANGE_LOGIN = 'ON_PASSWORD_CHANGE_LOGIN';
export const ON_LOGIN_INITIATE = 'ON_LOGIN_INITIATE';
export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS';
export const ON_LOGIN_FAILURE = 'ON_LOGIN_FAILURE';
export const ON_CLEAR_STATUS_ERRORS_MESSAGE_LOGIN = 'ON_CLEAR_STATUS_ERRORS_MESSAGE_LOGIN';

// Signup

export const ON_USERNAME_CHANGE_SIGNUP = 'ON_USERNAME_CHANGE_SIGNUP';
export const ON_EMAIL_CHANGE_SIGNUP = 'ON_EMAIL_CHANGE_SIGNUP';
export const ON_PASSWORD_CHANGE_SIGNUP = 'ON_PASSWORD_CHANGE_SIGNUP';
export const ON_CONFIRM_PASSWORD_CHANGE_SIGNUP = 'ON_CONFIRM_PASSWORD_CHANGE_SIGNUP';
export const ON_SIGNUP_INITIATE = 'ON_SIGNUP_INITIATE';
export const ON_SIGNUP_SUCCESS = 'ON_SIGNUP_SUCCESS';
export const ON_SIGNUP_FAILURE = 'ON_SIGNUP_FAILURE';
export const ON_CLEAR_STATUS_ERRORS_MESSAGE_SIGNUP = 'ON_CLEAR_STATUS_ERRORS_MESSAGE_SIGNUP';

// Navigation

export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';
export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
export const HIDE_SIGNUP_MODAL = 'HIDE_SIGNUP_MODAL';

// Categories
export const SHOW_UPLOADS_MODAL = 'SHOW_UPLOADS_MODAL';
export const HIDE_UPLOADS_MODAL = 'HIDE_UPLOADS_MODAL';

// Upload
export const ON_CHOOSE_IMAGE = 'ON_CHOOSE_IMAGE';
